# DigitalOcean App Platform Configuration
# Production-ready MeetNote deployment with full Whisper AI support

name: meetnote-production
region: nyc

# Environment variables (set these in DO dashboard)
envs:
- key: ENVIRONMENT
  value: production
- key: DEBUG
  value: "false"
- key: SECRET_KEY
  scope: RUN_TIME
  type: SECRET
- key: DATABASE_URL
  scope: RUN_TIME
  type: SECRET
- key: OPENROUTER_API_KEY
  scope: RUN_TIME
  type: SECRET
- key: DO_SPACES_KEY
  scope: RUN_TIME
  type: SECRET
- key: DO_SPACES_SECRET
  scope: RUN_TIME
  type: SECRET
- key: DO_SPACES_BUCKET
  value: meetnote-production
- key: DO_SPACES_REGION
  value: nyc3
- key: WHISPER_MODEL
  value: base
- key: WHISPER_DEVICE
  value: cpu
- key: WHISPER_COMPUTE_TYPE
  value: int8
- key: WHISPER_BEAM_SIZE
  value: "5"
- key: WHISPER_VAD_FILTER
  value: "true"
- key: MAX_AUDIO_SIZE
  value: "104857600"
- key: ENABLE_REAL_TIME_TRANSCRIPTION
  value: "true"
- key: ENABLE_AI_SUMMARIES
  value: "true"
- key: CORS_ORIGINS
  value: "https://meetnoteapp.netlify.app,https://meetnote-app.netlify.app,chrome-extension://*"

# Services configuration
services:
- name: meetnote-api
  source_dir: /backend
  github:
    repo: your-username/meetnote  # Update this with your GitHub repo
    branch: main
    deploy_on_push: true
  
  # Build configuration
  build_command: |
    pip install --upgrade pip
    pip install -r requirements-production.txt
  
  # Runtime configuration
  run_command: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 2
  
  # Resource allocation - Optimized for full Whisper AI
  instance_count: 1
  instance_size_slug: professional-xs  # 1GB RAM, 1 vCPU - $12/month
  
  # Disk space for Whisper models
  disk_size_gb: 1
  
  # Health check
  health_check:
    http_path: /api/health
    initial_delay_seconds: 60
    period_seconds: 30
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 3
  
  # HTTP configuration
  http_port: 8000
  
  # Routes
  routes:
  - path: /
  
  # CORS configuration
  cors:
    allow_origins:
    - exact: https://meetnoteapp.netlify.app
    - exact: https://meetnote-app.netlify.app
    - regex: ^chrome-extension://.*$
    allow_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    allow_headers:
    - Content-Type
    - Authorization
    - X-Requested-With
    allow_credentials: true

# Database configuration (managed PostgreSQL)
databases:
- name: meetnote-db
  engine: PG
  version: "15"
  size: db-s-1vcpu-1gb  # $15/month
  num_nodes: 1
  production: true

# Static sites (optional - for frontend if not using Netlify)
static_sites:
- name: meetnote-frontend
  source_dir: /frontend
  github:
    repo: your-username/meetnote  # Update this
    branch: main
    deploy_on_push: true
  build_command: |
    npm install
    npm run build
  output_dir: /dist
  index_document: index.html
  error_document: 404.html
  routes:
  - path: /app

# Jobs (for background tasks - optional)
jobs:
- name: cleanup-job
  source_dir: /backend
  github:
    repo: your-username/meetnote  # Update this
    branch: main
  build_command: pip install -r requirements-production.txt
  run_command: python scripts/cleanup_old_recordings.py
  instance_count: 1
  instance_size_slug: basic-xxs
  kind: PRE_DEPLOY  # Run before each deployment

# Alerts configuration
alerts:
- rule: CPU_UTILIZATION
  value: 80
- rule: MEM_UTILIZATION
  value: 85
- rule: RESTART_COUNT
  value: 5